name: flutter_web_diary
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  bloc_test: ^7.1.0
  firebase_storage_web: ^1.0.1
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: ^4.0.4
  firebase_auth: ^1.0.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  google_sign_in: ^4.5.9
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  rxdart: ^0.26.0
  equatable: ^2.0.0
  flutter_bloc: ^6.1.3
  bloc: ^6.1.3
  responsive_builder: ^0.3.0
  shared_preferences: ^2.0.3
  image_picker: ^0.7.2
  transparent_image: ^1.0.0
  path_provider:
  file_picker: ^3.0.1
  number_inc_dec: ^0.6.6
  url_strategy: ^0.2.0
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_storage: ^8.0.0
  desktop_window: ^0.4.0
  universal_platform: ^0.1.3
  cloud_firestore_mocks: ^0.7.0
  search_page: ^1.4.0
  country_state_city_picker: ^1.2.7
flutter:
  uses-material-design: true

  assets:
    - assets/
